# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: route_guide.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'route_guide.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11route_guide.proto\x12\x05proto\"\x97\x01\n\rPromptRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x16\n\x0estart_position\x18\x04 \x01(\t\x12\x14\n\x0c\x65nd_position\x18\x05 \x01(\t\x12\x12\n\nstart_date\x18\x06 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x07 \x01(\t\"S\n\x10TripPlanResponse\x12\x19\n\x04trip\x18\x01 \x01(\x0b\x32\x0b.proto.Trip\x12$\n\ndaily_plan\x18\x02 \x03(\x0b\x32\x10.proto.DailyPlan\"\xb9\x01\n\x04Trip\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x16\n\x0estart_position\x18\x04 \x01(\t\x12\x14\n\x0c\x65nd_position\x18\x05 \x01(\t\x12\x12\n\nstart_date\x18\x06 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x07 \x01(\t\x12\x12\n\ntotal_days\x18\x08 \x01(\x05\x12\x15\n\rroute_summary\x18\t \x01(\t\"I\n\tDailyPlan\x12\x0b\n\x03\x64\x61y\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12!\n\x08location\x18\x03 \x01(\x0b\x32\x0f.proto.Location\"o\n\x08Location\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12\x10\n\x08site_url\x18\x03 \x01(\t\x12\x10\n\x08latitude\x18\x04 \x01(\x01\x12\x11\n\tlongitude\x18\x05 \x01(\x01\x12\r\n\x05notes\x18\x06 \x01(\t2J\n\tAIService\x12=\n\x0cGeneratePlan\x12\x14.proto.PromptRequest\x1a\x17.proto.TripPlanResponseB%Z#github.com/Semhumc/grpc-proto/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'route_guide_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z#github.com/Semhumc/grpc-proto/proto'
  _globals['_PROMPTREQUEST']._serialized_start=29
  _globals['_PROMPTREQUEST']._serialized_end=180
  _globals['_TRIPPLANRESPONSE']._serialized_start=182
  _globals['_TRIPPLANRESPONSE']._serialized_end=265
  _globals['_TRIP']._serialized_start=268
  _globals['_TRIP']._serialized_end=453
  _globals['_DAILYPLAN']._serialized_start=455
  _globals['_DAILYPLAN']._serialized_end=528
  _globals['_LOCATION']._serialized_start=530
  _globals['_LOCATION']._serialized_end=641
  _globals['_AISERVICE']._serialized_start=643
  _globals['_AISERVICE']._serialized_end=717
# @@protoc_insertion_point(module_scope)
